{"uid":"e273e27e2357dcfb","name":"AuthE2ETests.AuthAndChangePassword_FullFlow_WorksCorrectly","fullName":"E2ETests:AuthE2ETests.AuthAndChangePassword_FullFlow_WorksCorrectly()","historyId":"9fb6d7470db8db7663f9a2b10bba0645","time":{"start":1761595709554,"stop":1761595710666,"duration":1112},"status":"broken","statusMessage":"An error occurred while saving the entity changes. See the inner exception for details.\n42P01: relation \"Users\" does not exist\n\nPOSITION: 13","statusTrace":"   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Update.Internal.BatchExecutor.ExecuteAsync(IEnumerable`1 commandBatches, IRelationalConnection connection, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Storage.RelationalDatabase.SaveChangesAsync(IList`1 entries, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(IList`1 entriesToSave, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.ChangeTracking.Internal.StateManager.SaveChangesAsync(StateManager stateManager, Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)\n   at Npgsql.EntityFrameworkCore.PostgreSQL.Storage.Internal.NpgsqlExecutionStrategy.ExecuteAsync[TState,TResult](TState state, Func`4 operation, Func`4 verifySucceeded, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.DbContext.SaveChangesAsync(Boolean acceptAllChangesOnSuccess, CancellationToken cancellationToken)\n   at AuthE2ETests.InitializeAsync() in /__w/TESTANDWEB/TESTANDWEB/src/Detective/E2ETests/Rest/AuthTests.cs:line 38\n   at Xunit.Sdk.TestInvoker`1.<RunAsync>b__46_0() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 173\n   at Xunit.Sdk.ExceptionAggregator.RunAsync[T](Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 107\n   at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)\n   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)\n   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)\n   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)\n   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)\n   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)\n   at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Storage.RelationalCommand.ExecuteReaderAsync(RelationalCommandParameterObject parameterObject, CancellationToken cancellationToken)\n   at Microsoft.EntityFrameworkCore.Update.ReaderModificationCommandBatch.ExecuteAsync(IRelationalConnection connection, CancellationToken cancellationToken)","flaky":false,"newFailed":false,"newBroken":false,"newPassed":false,"retriesCount":0,"retriesStatusChange":false,"beforeStages":[],"afterStages":[],"labels":[{"name":"thread","value":".NET Long Running Task"},{"name":"host","value":"cffca19ee0cd"},{"name":"language","value":"C#"},{"name":"framework","value":"xUnit.net"},{"name":"testClass","value":"AuthE2ETests"},{"name":"testMethod","value":"AuthAndChangePassword_FullFlow_WorksCorrectly"},{"name":"package","value":"AuthE2ETests"},{"name":"resultFormat","value":"allure2"}],"parameters":[],"links":[],"hidden":false,"retry":false,"extra":{"severity":"normal","retries":[],"categories":[{"name":"Test defects","matchedStatuses":[],"flaky":false}],"history":{"statistic":{"failed":0,"broken":3,"skipped":0,"passed":1,"unknown":0,"total":4},"items":[{"uid":"42610c5f6d6cc366","reportUrl":"https://FrozenLucifer.github.io/TESTANDWEB/26//#testresult/42610c5f6d6cc366","status":"broken","statusDetails":"An exception has been raised that is likely due to a transient failure.\nFailed to connect to 127.0.0.1:5432\nConnection refused","time":{"start":1761594768578,"stop":1761594769674,"duration":1096}},{"uid":"dcf8007ca07bf19e","reportUrl":"https://FrozenLucifer.github.io/TESTANDWEB/25//#testresult/dcf8007ca07bf19e","status":"broken","statusDetails":"An exception has been raised that is likely due to a transient failure.\nFailed to connect to 127.0.0.1:5432\nConnection refused","time":{"start":1761591447137,"stop":1761591448202,"duration":1065}},{"uid":"3a28617a790cbfcc","reportUrl":"https://FrozenLucifer.github.io/TESTANDWEB/24//#testresult/3a28617a790cbfcc","status":"passed","statusDetails":"","time":{"start":1761070725389,"stop":1761070727404,"duration":2015}}]},"tags":[]},"source":"e273e27e2357dcfb.json","parameterValues":[]}